# Generated by Django 5.2.11 on 2026-02-19 18:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('market_release_date', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('factory', 'Завод'), ('retail', 'Розничная сеть'), ('individual', 'Индивидуальный предприниматель')], max_length=20, verbose_name='Тип звена')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('debt', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Задолженность (в копейках)')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='elogistic.networknode', verbose_name='Поставщик')),
                ('products', models.ManyToManyField(related_name='nodes', to='elogistic.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Звено сети',
                'verbose_name_plural': 'Звенья сети',
            },
        ),
    ]
